engines:
    phpcodesniffer:
        enabled: true
        checks:
            Generic WhiteSpace ScopeIndent IncorrectExact:
                enabled: false
    phpmd:
        enabled: true
        checks:
            UnusedLocalVariable:
                enabled: false
            CleanCode/StaticAccess:
                enabled: false
